[project]
name = "telegram-group-tag-bot"
version = "0.0.1"
description = "Group members tagging solution"

[organization]
name = "IASA Student Council"
email = "studrada@gmail.com"

[details]
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.11"