[project]
name = "telegram-group-tag-bot"
version = "0.0.1"
description = "Group members tagging solution"
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }

[project.organization]
name = "IASA Student Council"
email = "studrada@gmail.com"

[[project.authors]]
name = "Yulian Zavodnyk"
email = "yulianzavodnyk@gmail.com"