version: 1
disable_existing_loggers: False

formatters:
    simple:
        format: '%(asctime)s - %(levelname)s - %(filename)s - %(message)s'
        datefmt: '%d-%m-%Y %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    file:
        class: logging.FileHandler
        level: WARNING
        formatter: simple
        filename: bot_logs.log
        mode: a

loggers:
    development:
        level: DEBUG
        handlers: [console]
        propagate: no

    staging:
        level: INFO
        handlers: [console, file]
        propagate: no

    production:
        level: WARNING
        handlers: [file]
        propagate: no

    pymongo:
        level: WARNING
        handlers: [console, file]
        propagate: False

    motor:
        level: WARNING
        handlers: [console, file]
        propagate: False

    aiogram:
        level: INFO
        handlers: [console, file]
        propagate: False

    telethon:
        level: INFO
        handlers: [console, file]
        propagate: False

root:
    level: DEBUG
    handlers: [console]